### ISSUE TITLE
GitHub Actions でビルド

### ISSUE THREAD

**Issue by YusukeHosonuma** [YusukeHosonuma/UserDefaultsBrowser#17]
Example プロジェクトをビルドするのがよさそう。（Public API が壊れてないかの確認にもなるので）

**Comment by maiyama18** [comment]
いいですね！CI として PR ごとに UIKit / SwiftUI それぞれの scheme を build する想定で #20 を作りました。もし何らかの想定が違ってたら言ってください 🙏

**Comment by YusukeHosonuma** [comment]
まさかこんなに早く対応して下さる方がいるとは思いませんでした。
想定バッチリです、またしても PR くださって本当にありがとうございます 👍 

P.S.
もし、PR での実行時間が長過ぎるようであれば PR では本体のみ、main ブランチで Example を含めたフルビルド、というのを考えていたのですが、現状の実行時間を見るかぎり負担にはならなそうですね！

**Comment by maiyama18** [comment]
レビューありがとうございます！先日 PR を出したときに壊してないかちょっと不安だなと思っていて、ちょうど issue があったので対応しました 😃 

なるほどー、言われてみると

> PR では本体のみ、main ブランチで Example を含めたフルビルド

はいいですね 👍 mac の actions は油断すると quota を食い潰しちゃう印象なので気になるレベルになってきたら対応した方がいいかもです。もしそのときメンションいただければ自分の方でやってみます！
